# Generated by Django 5.2.5 on 2025-09-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='users/profile/i.jpeg', upload_to='users/profile'),
        ),
    ]
